name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Aquí está el cambio clave: HEAD:main
        run: git push --force https://mauriciof68:${HF_TOKEN}@huggingface.co/spaces/mauriciof68/motor-ia-taller HEAD:main